version: "3.8"

services:

  quotes_grabber:
    build: ./quotes_grabber
    container_name: quotes_grabber
    restart: always
    environment:
      - APP_NAME=QuotesGrabber
    volumes:
      - './quotes_grabber:/app'
    expose:
      - 8080
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - './frontend:/app'
    ports:
      - '8000:8000'
      - '5000:5000'
